matrix:
  include:
    - node_js: node
      language: node_js
      script: npm run test:cover && npm run lint
      cache:
        directories:
          - node_modules
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - r: oldrel
      language: r
      cache: packages
    - r: release
      language: r
      cache: packages
      before_cache:
        - Rscript -e 'remotes::install_cran("pkgdown")'
        - Rscript -e 'remotes::install_github("JohnCoene/tippy")'
      after_success:
        - Rscript -e 'covr::codecov()'
        - R CMD INSTALL ${PKG_TARBALL}
        - Rscript pkgdown/build-docs.R
      deploy:
        provider: pages
        local_dir: docs
        skip_cleanup: true
        github_token: $GITHUB_TOKEN

apt_packages:
  - libfribidi-dev
  - libharfbuzz-dev
